// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __bigReg_h__
#define __bigReg_h__

#include "bigReg_RcppExports.h"

#endif // __bigReg_h__
