// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __bigReg_RcppExports_h__
#define __bigReg_RcppExports_h__

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace bigReg {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("bigReg", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("bigReg", "bigReg_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in bigReg");
            }
        }
    }

    inline Rcpp::List XWXMatrixW(arma::mat X, arma::mat y, arma::vec W) {
        typedef SEXP(*Ptr_XWXMatrixW)(SEXP,SEXP,SEXP);
        static Ptr_XWXMatrixW p_XWXMatrixW = NULL;
        if (p_XWXMatrixW == NULL) {
            validateSignature("Rcpp::List(*XWXMatrixW)(arma::mat,arma::mat,arma::vec)");
            p_XWXMatrixW = (Ptr_XWXMatrixW)R_GetCCallable("bigReg", "bigReg_XWXMatrixW");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_XWXMatrixW(Rcpp::wrap(X), Rcpp::wrap(y), Rcpp::wrap(W));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::List >(__result);
    }

    inline Rcpp::List SVD(Rcpp::List out, double epsilon) {
        typedef SEXP(*Ptr_SVD)(SEXP,SEXP);
        static Ptr_SVD p_SVD = NULL;
        if (p_SVD == NULL) {
            validateSignature("Rcpp::List(*SVD)(Rcpp::List,double)");
            p_SVD = (Ptr_SVD)R_GetCCallable("bigReg", "bigReg_SVD");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_SVD(Rcpp::wrap(out), Rcpp::wrap(epsilon));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::List >(__result);
    }

    inline Rcpp::List XWXMatrix(arma::mat X, arma::mat y) {
        typedef SEXP(*Ptr_XWXMatrix)(SEXP,SEXP);
        static Ptr_XWXMatrix p_XWXMatrix = NULL;
        if (p_XWXMatrix == NULL) {
            validateSignature("Rcpp::List(*XWXMatrix)(arma::mat,arma::mat)");
            p_XWXMatrix = (Ptr_XWXMatrix)R_GetCCallable("bigReg", "bigReg_XWXMatrix");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_XWXMatrix(Rcpp::wrap(X), Rcpp::wrap(y));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::List >(__result);
    }

}

#endif // __bigReg_RcppExports_h__
